(MAIN::semn prioritate stop)
(MAIN::urgenta aparitie_animal)
(MAIN::semnal rotire_brat)
(MAIN::semafor galben)
(MAIN::marcaj linie_intrerupta)
(MAIN::semn interzicere sfarsit_interzicerii_de_depasire)
;(MAIN::semn prioritate obligatoriu_la_dreapta)
(MAIN::semn prioritate obligatoriu_in_fata)
(MAIN::max-speed 100)
(MAIN::nod sursa1 intermediar1 rapid stanga)
(MAIN::nod sursa1 intermediar1 normal fata)
(MAIN::nod sursa1 intermediar1 normal dreapta)
